name = "abcdeZ"
uuid = "208e7efd-7036-4c82-8b73-3e7ae71c2350"
authors = ["mauricelanghinrichs <m.langhinrichs@icloud.com>"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
